drivers: input: touchscreen: fts_521: guard some unused vars behind GRIP_MODE_DEBUG
../drivers/input/touchscreen/fts_521/fts.c:5999:5: error: unused variable 'grip_rcmd' [-Werror,-Wunused-variable]
 5999 |         u8 grip_rcmd[2] = { 0xc1, 0x08 };
      |            ^~~~~~~~~
../drivers/input/touchscreen/fts_521/fts.c:6000:5: error: unused variable 'grip_value' [-Werror,-Wunused-variable]
 6000 |         u8 grip_value[2] = {
      |            ^~~~~~~~~~
2 errors generated.

Signed-off-by: fukiame <fukiame@proton.me>