scsi: ufs: guard some unused functions behind CONFIG_TRACEPOINTS
../drivers/scsi/ufs/ufshcd.c:623:13: error: unused function 'ufshcd_add_cmd_upiu_trace' [-Werror,-Wunused-function]
  623 | static void ufshcd_add_cmd_upiu_trace(struct ufs_hba *hba, unsigned int tag,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/scsi/ufs/ufshcd.c:759:13: error: unused function '__ufshcd_cmd_log' [-Werror,-Wunused-function]
  759 | static void __ufshcd_cmd_log(struct ufs_hba *hba, char *str, char *cmd_type,
      |             ^~~~~~~~~~~~~~~~
2 errors generated.

Signed-off-by: fukiame <fukiame@proton.me>