fixup! can: statistic: fix broken backport of 'use atomic access in hot path
pkg_stats does not exist here

../net/can/proc.c:125:37: error: use of undeclared identifier 'pkg_stats'; did you mean 'can_stats'?
  125 |         long tx_frames = atomic_long_read(&pkg_stats->tx_frames);
      |                                            ^~~~~~~~~
      |                                            can_stats
../net/can/proc.c:121:18: note: 'can_stats' declared here
  121 |         struct s_stats *can_stats = net->can.can_stats;
      |                         ^
../net/can/proc.c:126:35: error: use of undeclared identifier 'pkg_stats'; did you mean 'can_stats'?
  126 |         long matches = atomic_long_read(&pkg_stats->matches);
      |                                          ^~~~~~~~~
      |                                          can_stats
../net/can/proc.c:121:18: note: 'can_stats' declared here
  121 |         struct s_stats *can_stats = net->can.can_stats;
      |                         ^
../net/can/proc.c:127:43: error: use of undeclared identifier 'pkg_stats'; did you mean 'can_stats'?
  127 |         long rx_frames_delta = atomic_long_read(&pkg_stats->rx_frames_delta);
      |                                                  ^~~~~~~~~
      |                                                  can_stats
../net/can/proc.c:121:18: note: 'can_stats' declared here
  121 |         struct s_stats *can_stats = net->can.can_stats;
      |                         ^
../net/can/proc.c:128:43: error: use of undeclared identifier 'pkg_stats'; did you mean 'can_stats'?
  128 |         long tx_frames_delta = atomic_long_read(&pkg_stats->tx_frames_delta);
      |                                                  ^~~~~~~~~
      |                                                  can_stats
../net/can/proc.c:121:18: note: 'can_stats' declared here
  121 |         struct s_stats *can_stats = net->can.can_stats;
      |                         ^
../net/can/proc.c:129:41: error: use of undeclared identifier 'pkg_stats'; did you mean 'can_stats'?
  129 |         long matches_delta = atomic_long_read(&pkg_stats->matches_delta);
      |                                                ^~~~~~~~~
      |                                                can_stats
../net/can/proc.c:121:18: note: 'can_stats' declared here
  121 |         struct s_stats *can_stats = net->can.can_stats;
      |                         ^
6 errors generated.

Signed-off-by: fukiame <fukiame@proton.me>