drivers: supply: bq2597x: kill some unused functions
../drivers/power/supply/ti/bq2597x_charger.c:536:12: error: unused function 'bq2597x_set_wdt' [-Werror,-Wunused-function]
  536 | static int bq2597x_set_wdt(struct bq2597x *bq, int ms)
      |            ^~~~~~~~~~~~~~~
../drivers/power/supply/ti/bq2597x_charger.c:1189:12: error: unused function 'bq2597x_clear_alarm_int_mask' [-Werror,-Wunused-function]
 1189 | static int bq2597x_clear_alarm_int_mask(struct bq2597x *bq, u8 mask)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/power/supply/ti/bq2597x_charger.c:1223:12: error: unused function 'bq2597x_clear_fault_int_mask' [-Werror,-Wunused-function]
 1223 | static int bq2597x_clear_fault_int_mask(struct bq2597x *bq, u8 mask)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/power/supply/ti/bq2597x_charger.c:2232:13: error: unused function 'bq2597x_dump_reg' [-Werror,-Wunused-function]
 2232 | static void bq2597x_dump_reg(struct bq2597x *bq)
      |             ^~~~~~~~~~~~~~~~
4 errors generated.

Signed-off-by: fukiame <fukiame@proton.me>